# Generated by Django 5.1.7 on 2025-03-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_department'),
    ]

    operations = [
    ]
