# Generated by Django 5.2 on 2025-04-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compoleted',
            new_name='completed',
        ),
    ]
